POST http://localhost:3000
Content-Type: application/json
Accept-Language: pt

{
    "name": "John Doe",
    "cpf": 12345678900
}

### 

PUT http://localhost:3000/owner/45345678913
Content-Type: application/json
Accept-Language: pt

{
    "name": "Elysama Silva"
}

###
DELETE http://localhost:3000/owner/12345678900
Content-Type: application/json
Accept-Language: pt

